language: node_js
node_js:
    - 8.9

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install --quiet -g karma
    - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
    - export CHROME_BIN=chromium-browser

script:
    - ng test
    - ng e2e
